// Package gen -----------------------------
// @file      : test.go
// @author    : zhangtuo
// @contact   :
// @time      : 2023/10/23 18:51
// -------------------------------------------
package main

import (
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	var req pluginpb.CodeGeneratorRequest
	opts := protogen.Options{}
	plugin, err := opts.New(&req)
	if err != nil {
		return
	}
	if err != nil {
		panic(err)
	}
	g := plugin.NewGeneratedFile("test.gen.go", plugin.Files[len(plugin.Files)-1].GoImportPath)
	g.P("// code generated by protoc-gen-go-zhangtuo. DO NOT EDIT.")
	g.P("package ", plugin.Files[len(plugin.Files)-1].GoPackageName)
	//file := descriptorpb.FileDescriptorProto{}
	for _, f := range plugin.Files {
		if f.Generate {
			if err := generateFile(g, f); err != nil {
				return
			}
		}
	}
}

func generateFile(f *protogen.GeneratedFile, file *protogen.File) error {
	for _, svr := range file.Services {
		for _, method := range svr.Methods {
			if method.Desc.IsStreamingClient() || method.Desc.IsStreamingServer() {
				continue
			}
		}
	}
	return nil
}
