%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.19.7

-ifndef(msg_pb).
-define(msg_pb, true).

-define(msg_pb_gpb_version, "4.19.7").

-ifndef('TEST_MSG_PB_H').
-define('TEST_MSG_PB_H', true).
-record(test_msg,
        {msg = []               :: unicode:chardata() | undefined, % = 1, optional
         delayTime = 0          :: integer() | undefined, % = 2, optional, 32 bits
         rand = 0               :: integer() | undefined % = 3, optional, 32 bits
        }).
-endif.

-endif.
